server:
  port: 8082


mybatis:
  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill01?serverTimezone=GMT&useSSL=false&useUnicode=true&characterEncoding=utf-8
    name: seckill01
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false

    #配置redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 10

    #设置jedis连接池
    jedis:
      pool:
        max-active: 50
        min-idle: 20
